#!/bin/sh
. "$(dirname "$0")/_/husky.sh"



echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn prettify ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
yarn lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check test Standards
yarn test ||
(
        echo 'Test Check Failed. fix the test components and try to commit again.'
        false; 
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright.... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

npm run build ||
(
    echo 'Next build failed: View the errors above to see why. Commit aborted.';
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ All good... I am committing this now. ✅✅✅✅'