#Alpine
FROM node:16.14.2-alpine3.15 AS leagues-of-code-platform
#FROM node:14.7.0-alpine3.12 AS leagues-of-code-platform

ARG REACT_APP_ENV=dev

RUN apk add --no-cache git

COPY . .

RUN yarn install && yarn test

RUN if [[ $REACT_APP_ENV == dev ]]; then \
		yarn build_dev; \
	fi \
	&& if [[ $REACT_APP_ENV == stage ]]; then \
		yarn build_stage; \
	fi \
	&& if [[ $REACT_APP_ENV == prod ]]; then \
		yarn build_prod; \
	fi

#RUN export CI=true && yarn install && yarn test --passWithNoTests && yarn build


#Alpine
FROM nginx:1.17.10-alpine

EXPOSE 3000

RUN rm -rf /etc/nginx/conf.d/*
COPY docker/nginx/conf.d /etc/nginx/conf.d

COPY --from=leagues-of-code-platform /build /build